recipes-app/mindconnect-node-red-contrib-mindconnect/files/npm-shrinkwrap.json
recipes-app/mindconnect-node-red-contrib-mindconnect/mindconnect-node-red-contrib-mindconnect_3.7.0.bb
recipes-app/node-red-contrib-modbus/files/npm-shrinkwrap.json
recipes-app/node-red-contrib-modbus/node-red-contrib-modbus_5.13.2.bb
recipes-app/node-red-contrib-opcua/files/npm-shrinkwrap.json
recipes-app/node-red-contrib-opcua/node-red-contrib-opcua_0.2.62.bb
recipes-app/node-red-contrib-s7/files/npm-shrinkwrap.json
recipes-app/node-red-contrib-s7/node-red-contrib-s7_2.2.1.bb
recipes-app/node-red-dashboard/files/npm-shrinkwrap.json
recipes-app/node-red-dashboard/node-red-dashboard_2.22.1.bb
recipes-app/node-red-node-serialport/files/npm-shrinkwrap.json
recipes-app/node-red-node-serialport/node-red-node-serialport_0.10.2.bb
recipes-app/node-red-node-sqlite/files/npm-shrinkwrap.json
recipes-app/node-red-node-sqlite/node-red-node-sqlite_0.4.3.bb
recipes-core/images/iot2050-image-example.bb

Note that this will prolong our build further, likely eventually mitigated by having per-package buildchroots from Isar (to be developed).

Preinstall node red nodes

---

recipes-core/customizations-example/customizations-example_0.1-iot2050-debian.bb
recipes-core/customizations-example/files/20-swap-ethernet-port.rules

add the udev rules to swap the ethernet port name

ethernet: swap the ethernet port name

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update.py
recipes-app/iot2050-firmware-update/iot2050-firmware-update_0.1.bb
recipes-core/images/iot2050-image-example.bb

as needed update uboot from user space,provide update script

Provide uboot upgrade script

---

conf/distro/isar.conf
recipes-core/images/iot2050-image-example.bb
wic/iot2050.wks

Addresses 2 open issues and one with early released basic devices.
@bergmanu

Fixes and improvements

---

recipes-bsp/u-boot/files/upstream/0001-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/upstream/0002-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/upstream/0003-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/upstream/0004-net-eth-uclass-eth_get_dev-based-on-SEQ_ALIAS-instea.patch
recipes-bsp/u-boot/files/upstream/0005-net-eth-uclass-call-stop-only-for-active-devices.patch
recipes-bsp/u-boot/files/upstream/0006-misc-uclass-Introduce-misc_init_by_ofnode.patch
recipes-bsp/u-boot/files/upstream/0007-soc-ti-pruss-add-a-misc-driver-for-PRUSS-in-TI-SoCs.patch
recipes-bsp/u-boot/files/upstream/0008-remoteproc-pruss-add-PRU-remoteproc-driver.patch
recipes-bsp/u-boot/files/upstream/0009-net-ti-icssg-prueth-Add-ICSSG-ethernet-driver.patch
recipes-bsp/u-boot/files/upstream/0010-arm-dts-k3-am65-main-Add-msmc_ram-node.patch
recipes-bsp/u-boot/files/upstream/0011-arm-dts-k3-am654-base-board-u-boot-Add-icssg-specifi.patch
recipes-bsp/u-boot/files/upstream/0012-arm-dts-k3-am65-main-Add-scm_conf-node.patch
recipes-bsp/u-boot/files/upstream/0013-arm-dts-k3-am65-main-Add-pruss-nodes-for-ICSSG2.patch
recipes-bsp/u-boot/files/upstream/0014-arm64-dts-ti-am654-base-board-add-ICSSG2-Ethernet-su.patch
recipes-bsp/u-boot/files/upstream/0015-configs-am65x_evm_a53_defconfig-Enable-prueth-config.patch
recipes-bsp/u-boot/files/upstream/0016-net-ti-icssg-prueth-Drop-unsupported-modes-from-the-.patch
recipes-bsp/u-boot/files/upstream/0017-net-ti-icssg-prueth-use-constants-instead-of-hardcod.patch
recipes-bsp/u-boot/files/upstream/0018-net-ti-icssg-prueth-use-a-single-chn_name-variable-i.patch
recipes-bsp/u-boot/files/upstream/0019-net-ti-icssg-prueth-Add-port-speed-duplex-command.patch
recipes-bsp/u-boot/files/upstream/0020-net-ti-icssg-prueth-Add-shutdown-command.patch
recipes-bsp/u-boot/files/upstream/0021-net-ti-icssg-prueth-Auto-start-PRU-and-RTU-when-star.patch
recipes-bsp/u-boot/files/upstream/0022-config_distro_bootcmd-Add-platform-start-script-hook.patch
recipes-bsp/u-boot/files/upstream/0023-arm-dts-k3-am65-main-Add-ICSSG0-1-nodes.patch
recipes-bsp/u-boot/files/upstream/0024-iot2050-Add-ICSSG0-Ethernet-support.patch
recipes-bsp/u-boot/files/upstream/0025-iot2050-config-the-default-device-tree.patch
recipes-bsp/u-boot/u-boot-iot2050-2021.x-upstream.inc

take the u-boot commit:51f65b506f37252acb3cd4184ef5e1fc20da13a2 as the
base.patch the modify for our board

iot2050: organizing the recipes of u-boot in the form of patch

---

recipes-bsp/u-boot/u-boot-iot2050-2021.x-upstream.inc

as not specify the work source, the patch can not be merged  into the repo.

bugfix: Specify the work source

---

.gitlab-ci.yml
kas-container

Comes with a number of smaller improvements, e.g. the elimination of the
"Exception ignored when ..." warnings after builds and support for
multi-arch containers (arm64-hosted builds).

Update to kas 2.4

---

recipes-app/iot2050setup/files/iot2050setup.py

doing the reset command behind the cp2102 configure

iot2050setup: doing reset command when all the configuration done

---

recipes-app/mraa/files/0001-aio.c-fix-mraa_aio_set_bit-for-result-scaling.patch
recipes-app/mraa/files/0002-feat-iot2050-add-iot2050-platform-support.patch
recipes-app/mraa/files/0003-feat-iot2050-add-some-example-code-for-testing.patch
recipes-app/mraa/files/0004-api-Add-explicit-close-methods-to-classes.patch
recipes-app/mraa/files/0005-gpio-chardev-Add-helper-to-retrieve-gpiochip-and-lin.patch
recipes-app/mraa/files/0006-gpio-chardev-Add-function-to-retrieve-sysfs-base-for.patch
recipes-app/mraa/files/0007-iot2050-Switch-to-runtime-detection-of-gpiochip-numb.patch
recipes-app/mraa/files/0008-iot2050-Add-USER-button.patch
recipes-app/mraa/files/0009-led-Fix-and-cleanup-initialization.patch
recipes-app/mraa/files/0010-uart-Fix-software-flow-control-management.patch
recipes-app/mraa/files/0011-gpio-Avoid-spurious-value-reset-without-output-mode-.patch
recipes-app/mraa/mraa_2.2.0.bb

Both patches (and more) also pending for mraa upstream.

mraa: Add patches that fix mraa_uart_set_flowcontrol and improves mraa_gpio_dir

---

.github/workflows/main.yml
README.md
conf/distro/iot2050-debian.conf
isar-patches/0001-wic-plugins-Improve-rootfs-u-boot-script_prepend-pas.patch
kas-container
kas/iot2050.yml
wic/iot2050.wks

@gylstorffq, this brings an isar update you can also use.

Update kas & isar / add containerized SDK

---

conf/distro/debian-snapshot.list

Freeze at Sep. 2 2021.
Signed-off-by: Su Bao Cheng <baocheng.su@siemens.com>

Freeze bullseye code base

---

recipes-bsp/u-boot/files/0002-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/0003-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0004-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0005-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0006-watchdog-Allow-to-use-CONFIG_WDT-without-starting-wa.patch
recipes-bsp/u-boot/files/0007-iot2050-Enable-watchdog-support-but-do-not-auto-star.patch
recipes-bsp/u-boot/files/0008-sf-Querying-write-protect-status-before-operating-th.patch

Should obsolete #192 but I was not able to test this.

Fix U-Boot DT for 2.0 mode

---

recipes-app/node-red-gpio/files/0006-node-red-gpio-Add-support-for-initial-message-from.patch
recipes-app/node-red-gpio/node-red-gpio_0.0.6-IOT2050.bb

Port a part of siemens/meta-iot2000@5fc2bbed commit related to DIN's
initial message support.
Fixes #156
Signed-off-by: Ivan Mikhaylov <ivan.mikhaylov@siemens.com>

node-red-gpio: port DIN's initial message from iot2000

---

.gitignore

add meta-coral to ignore list

---

.github/workflows/free-disk-space/action.yml
kas/iot2050.yml

Primarily brings TensorFlow update to 2.5.3.

Update meta-coral layer

---

CONTRIBUTING.md
README.md

Just a tip to add in the README.md, which might be useful for those are not used to use docker/containers. Without this suggestion, the user at its first try will receive a permission error. Trying to run the script as root, it will be said to do not do that.

Improved README.md and CONTRIBUTING.md

---

Kconfig
kas/opt/docker.yml
recipes-core/images/iot2050-image-example.bb

For now,  I want to make the software configurable and optional. At present, the preinstalled software and some of our custom software have been made configurable
It's still a draft, Please help to review whether this approach is appropriate

integrate docker support

---

.github/workflows/free-disk-space/action.yml

ci: Extend package removal list to avoid pulling alternatives

---

Kconfig
README.md
recipes-core/images/iot2050-image-base.bb

1. kconfig: Improve the hit for the debian mirror URL, `http://` protocol prefix is necessary.
2. Link generated .wic to .wic.img for better backward compatibility.

Some minor Changes

---

.github/workflows/free-disk-space/action.yml

Stable V01.03: Fix CI

---

recipes-app/iot2050setup/files/iot2050setup.py

The current code was not compatible with consoles delivering the result of escape sequence in fragments or even byte-wise. Adjust things for that and also simplify the logic in way that we no longer need to switch to non-blocking mode.

iot2050setup: Fix reading back console size values and simplify code

---

classes/npm.bbclass
conf/distro/iot2050-debian.conf
conf/distro/preferences.upstream-libssl
kas/iot2050.yml
recipes-app/iot2050-firmware-update/iot2050-firmware-update_0.4.bb
recipes-app/mraa/mraa_2.2.0+git.bb
recipes-app/node-red-contrib-opcua/node-red-contrib-opcua_0.2.289.bb
recipes-app/node-red-gpio/node-red-gpio_0.3.0+git.bb
recipes-app/node-red-node-serialport/node-red-node-serialport_1.0.1.bb
recipes-app/node-red/node-red_2.2.3.bb
recipes-app/tcf-agent/tcf-agent.bb
recipes-bsp/k3-rti-wdt/k3-rti-wdt_1.1.bb
recipes-bsp/optee-os/optee-os-iot2050_3.19.0.bb
recipes-bsp/secure-boot-otp-provisioning/secure-boot-otp-provisioning_0.1.bb
recipes-bsp/u-boot/u-boot-iot2050.inc
recipes-core/images/iot2050-image-example.bb
recipes-core/images/iot2050-image-swu-example.bb
recipes-core/iot2050-firmware/iot2050-firmware_0.1.bb
recipes-core/swupdate-complete-update-helper/swupdate-complete-update-helper_0.1.bb
recipes-initramfs/iot2050-initramfs/iot2050-initramfs_0.1.bb
recipes-security/openssl/openssl_latest.bb
wic/iot2050-swu-secure.wks.in
wic/iot2050-swu.wks.in

Work in progress: more testing needed, and one more catch-up with isar-cip-core is missing.
@adriaan42

Update Isar layers, improve openssl rebuild

---

recipes-bsp/patch-u-boot-env/patch-u-boot-env_0.1.bb

Add missing RT deps for patch-u-boot-env

---

recipes-bsp/u-boot/files/0020-iot2050-Refactor-the-m.2-and-minipcie-power-pin.patch
recipes-bsp/u-boot/u-boot-iot2050_2022.10.inc
recipes-kernel/linux/files/patches-5.10/0221-arm64-dts-ti-iot2050-Refactor-the-m.2-and-minipcie-p.patch

Replay #430 to master.
However the new FS number is not decided, that's why this PR is marked as draft, I will update it once the new FS number is fixed.

Make m.2 power control also avaiable to minipcie

---

recipes-bsp/ti-pruss-firmware/ti-pruss-firmware_08.06.00.007.bb
recipes-kernel/linux/files/patches-5.10/0222-net-ethernet-ti-icssg_prueth-Remove-Rx-enable-in-ini.patch
recipes-kernel/linux/files/patches-5.10/0223-net-ethernet-ti-icssg_prueth-Initialize-emac-speed-o.patch

Addresses one regression on PG1 and addresses some startup issues on PG2 devices.

Fixes for Ethernet driver

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update.tmpl

Make the firmware update go with a more reasonable logic and a better prompt

iot2050-firmware-update: Refactor the update logic

---

classes/npm.bbclass
recipes-devtools/sbuild-chroot/sbuild-chroot-target-npm.bb

Let's wait till this has been integrated upstream.
closes: #432

feat: use dedicated schroot to speedup npm builds

---

recipes-bsp/ti-pruss-firmware/ti-pruss-firmware_09.00.00.005.bb

This is supposed to fix remaining start-up issues, e.g. https://github.com/siemens/meta-iot2050/issues/108

ti-pruss-firmware: Update to 09.00.00.005

---

isar-patches/0001-meta-optee-client-Generalize-and-update-shutdown-rul.patch
kas/iot2050.yml

Add Isar patch to fix/improve tee-supplicant shutdown rules

---

recipes-bsp/u-boot/files/0005-iot2050-Allow-for-more-than-1-USB-storage-device.patch
recipes-bsp/u-boot/u-boot-iot2050_2023.10.bb

u-boot-iot2050: Add patch to restore up to 3 USB storag devices

---

conf/distro/debian-snapshot.list

New timestamp is 20231023T151630Z of Debian 12.

Freeze debian package version

---

CONTRIBUTING.md

CONTRIBUTING: Add how to generate git patch files

---

README.md
recipes-core/swupdate-complete-update-helper/swupdate-complete-update-helper_0.1.bb

Outcome of the discussion in #517.

Improve swupdate completion documentation

---

recipes-app/iot2050-eio-manager/iot2050-eio-manager_0.1.bb
recipes-core/customizations-example/files/20-create-symbolic-link-for-serial-port.rules

Addressing the ttyX30 link setup on PG1 Advanced and fixes a build warning of the EIO manager.

Small fixes

---

recipes-app/iot2050-eio-manager/iot2050-eio-manager_0.1.bb

Add libfuse-dev to example image

---

.github/workflows/main.yml

Resolves Node.js deprecation warnings.

ci: Update actions

---

meta-hailo/recipes-app/tappas/README.md
meta-hailo/recipes-app/tappas/files/debian/rules
recipes-app/tcf-agent/tcf-agent.bb

[meta-hailo: Polish the format and description of tappas](https://github.com/siemens/meta-iot2050/commit/84a2ae2682083a3ebd53bf3a2742ae42c5e2a637)
[tcf-agent: Fix the unused upstream link](https://github.com/siemens/meta-iot2050/commit/e7816419e56c9ee58348491bae00312c20b34300)

tcf-agent: Fix the unused upstream link

---

meta-hailo/recipes-app/tappas/README.md
meta-hailo/recipes-app/tappas/files/debian/hailo-post-processes.install
meta-hailo/recipes-app/tappas/files/patches/0002-Do-not-install-binaries-without-clear-license-clarif.patch
meta-hailo/recipes-app/tappas/tappas_3.29.1.bb

Do not install binaries without clear license clarification

meta-hailo: Remove tappas binaries

---

README.md
recipes-core/images/iot2050-image-example.bb
recipes-devtools/firmware-update-package/firmware-update-package_0.1.bb

Ensure that the firmware update package is correctly generated and included in the final image, facilitating the firmware update process for the IOT2050 device.

firmware-update-package: Package the tarball into the image
