recipes-core/regen-rootfs-uuid/files/regen-rootfs-uuid.sh

See also https://support.industry.siemens.com/tf/ww/en/posts/exampla-image-only-starts-once/237158/?page=0&pageSize=10#post929842

regen-rootfs-uuid: Reduce risk of image corruption on hard-reset

---

.gitignore
recipes-core/customizations-base/customizations-base_0.1-iot2050-debian.bb

Taken from jailhouse-images: Allow to enhance the customizations-base
package via a local.inc that is outside of versioning control, e.g. to
inject wifi credentials or authorized ssh keys.
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

customizations-base: Allow local extensions

---

recipes-app/tcf-agent/files/debian/tcf-agent.service

Doesn't work (lacks cert generation e.g.) but also doesn't add any value
because there is no authentication anyway with tcf-agent.

tcf-agent: Disable SSL transport encryption

---

conf/distro/isar.conf

libjson-c is needed for linking against mraa. And zlib1g-dev should come
for the target architecture.
Closes: #62

sdk: Add libjson-c, fix zlib arch

---

conf/distro/preferences.npm-backport

Something changed in buster-backports, breaking the simple selection of
all node-* packages from there. We need to keep four of them at stable
versions.

Fix backport package selection for npm

---

recipes-kernel/linux/files/0018-refined-basic-board-dts.patch
recipes-kernel/linux/linux-iot2050_4.19.94+.bb

as released basic board has ospi compat settings.
Refined the basic dts to compat the released basic board and currently sysfw abi3.x
about opsi

refine basic board dts

---

recipes-app/iot2050setup/files/iot2050setup.py
recipes-core/customizations-example/files/board-configuration
recipes-kernel/linux/files/0001-iot2050-add-iot2050-platform-support.patch
recipes-kernel/linux/files/0002-Add-support-for-U9300C-TD-LTE-module.patch
recipes-kernel/linux/files/0003-feat-Add-CP210x-driver-support-to-software-flow-cont.patch
recipes-kernel/linux/files/0004-fix-disable-usb-lpm-to-fix-usb-device-reset.patch
recipes-kernel/linux/files/0005-Fix-DP-maybe-not-display-problem.patch
recipes-kernel/linux/files/0006-fix-fix-the-hardware-flow-function-of-cp2102n24.patch
recipes-kernel/linux/files/0007-feat-add-io-expander-pcal9535-support.patch
recipes-kernel/linux/files/0008-setting-the-RJ45-port-led-behavior.patch
recipes-kernel/linux/files/0009-fix-clear-the-cycle-buffer-of-serial.patch
recipes-kernel/linux/files/0010-feat-extend-led-panic-indicator-on-and-off.patch
recipes-kernel/linux/files/0011-fix-can-not-auto-negotiate-to-100M-with-4-wire.patch
recipes-kernel/linux/files/0012-feat-change-mmc-order-using-alias-in-dts.patch
recipes-kernel/linux/files/0013-fix-PLL4_DCO-freq-over-range-cause-DP-not-display.patch
recipes-kernel/linux/files/0014-iot2050-Provide-dtb-for-devices-using-boot-load-V01..patch
wic/iot2050.wks

Extract oldfw related changes to k3-am65-iot2050-oldfw.dtsi, includes
uart dma workaround and the clock swapping of sdhci. Also change the
includings correspondingly.
Remove the word 'common' from iot2050.dtsi, sarcasticly our boards have
a lot that not in common.
Change the compatible and model string according to Jan's upstreaming
patch.
Change the dr_mode of usb1 to `host`.
Change board name in iot2050setup.py and board-configuration

refine kernel device tree

---

wic/iot2050.wks

The dtb paths in boot.scr are wrongly swapped between am6528 and am6548.
Signed-off-by: Su Baocheng <baocheng.su@siemens.com>

linux: Fix dtb path error in boot.scr

---

recipes-bsp/u-boot/files/upstream/0001-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/upstream/0002-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/upstream/0003-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/upstream/0004-net-eth-uclass-eth_get_dev-based-on-SEQ_ALIAS-instea.patch
recipes-bsp/u-boot/files/upstream/0005-net-eth-uclass-call-stop-only-for-active-devices.patch
recipes-bsp/u-boot/files/upstream/0006-misc-uclass-Introduce-misc_init_by_ofnode.patch
recipes-bsp/u-boot/files/upstream/0007-soc-ti-pruss-add-a-misc-driver-for-PRUSS-in-TI-SoCs.patch
recipes-bsp/u-boot/files/upstream/0008-remoteproc-pruss-add-PRU-remoteproc-driver.patch
recipes-bsp/u-boot/files/upstream/0009-net-ti-icssg-prueth-Add-ICSSG-ethernet-driver.patch
recipes-bsp/u-boot/files/upstream/0010-arm-dts-k3-am65-main-Add-msmc_ram-node.patch
recipes-bsp/u-boot/files/upstream/0011-arm-dts-k3-am654-base-board-u-boot-Add-icssg-specifi.patch
recipes-bsp/u-boot/files/upstream/0012-arm-dts-k3-am65-main-Add-scm_conf-node.patch
recipes-bsp/u-boot/files/upstream/0013-arm-dts-k3-am65-main-Add-pruss-nodes-for-ICSSG2.patch
recipes-bsp/u-boot/files/upstream/0014-arm64-dts-ti-am654-base-board-add-ICSSG2-Ethernet-su.patch
recipes-bsp/u-boot/files/upstream/0015-configs-am65x_evm_a53_defconfig-Enable-prueth-config.patch
recipes-bsp/u-boot/files/upstream/0016-net-ti-icssg-prueth-Drop-unsupported-modes-from-the-.patch
recipes-bsp/u-boot/files/upstream/0017-net-ti-icssg-prueth-use-constants-instead-of-hardcod.patch
recipes-bsp/u-boot/files/upstream/0018-net-ti-icssg-prueth-use-a-single-chn_name-variable-i.patch
recipes-bsp/u-boot/files/upstream/0019-net-ti-icssg-prueth-Add-port-speed-duplex-command.patch
recipes-bsp/u-boot/files/upstream/0020-net-ti-icssg-prueth-Add-shutdown-command.patch
recipes-bsp/u-boot/files/upstream/0021-net-ti-icssg-prueth-Auto-start-PRU-and-RTU-when-star.patch
recipes-bsp/u-boot/files/upstream/0022-config_distro_bootcmd-Add-platform-start-script-hook.patch
recipes-bsp/u-boot/files/upstream/0023-arm-dts-k3-am65-main-Add-ICSSG0-1-nodes.patch
recipes-bsp/u-boot/files/upstream/0024-iot2050-Add-ICSSG0-Ethernet-support.patch
recipes-bsp/u-boot/files/upstream/0025-iot2050-config-the-default-device-tree.patch
recipes-bsp/u-boot/files/upstream/0026-enable-soc-device-ID-driver.patch
recipes-bsp/u-boot/u-boot-iot2050-2021.x-upstream.inc

This allows Texas Instruments Keystone 3 SoCs to identify
specifics about the SoC in use

feat: enable soc device ID driver

---

.github/workflows/main.yml

Seems we overflow some log limits on github now. Splitting up will also
speed up the completion, at the price of building the common pieces of
both images twice.

ci: Run RT image build in separate job

---

recipes-bsp/u-boot/files/upstream/0001-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/upstream/0002-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/upstream/0003-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/upstream/0004-net-eth-uclass-eth_get_dev-based-on-SEQ_ALIAS-instea.patch
recipes-bsp/u-boot/files/upstream/0005-net-eth-uclass-call-stop-only-for-active-devices.patch
recipes-bsp/u-boot/files/upstream/0006-misc-uclass-Introduce-misc_init_by_ofnode.patch
recipes-bsp/u-boot/files/upstream/0007-soc-ti-pruss-add-a-misc-driver-for-PRUSS-in-TI-SoCs.patch
recipes-bsp/u-boot/files/upstream/0008-remoteproc-pruss-add-PRU-remoteproc-driver.patch
recipes-bsp/u-boot/files/upstream/0009-net-ti-icssg-prueth-Add-ICSSG-ethernet-driver.patch
recipes-bsp/u-boot/files/upstream/0010-arm-dts-k3-am65-main-Add-msmc_ram-node.patch
recipes-bsp/u-boot/files/upstream/0011-arm-dts-k3-am654-base-board-u-boot-Add-icssg-specifi.patch
recipes-bsp/u-boot/files/upstream/0012-arm-dts-k3-am65-main-Add-scm_conf-node.patch
recipes-bsp/u-boot/files/upstream/0013-arm-dts-k3-am65-main-Add-pruss-nodes-for-ICSSG2.patch
recipes-bsp/u-boot/files/upstream/0014-arm64-dts-ti-am654-base-board-add-ICSSG2-Ethernet-su.patch
recipes-bsp/u-boot/files/upstream/0015-configs-am65x_evm_a53_defconfig-Enable-prueth-config.patch
recipes-bsp/u-boot/files/upstream/0016-net-ti-icssg-prueth-Drop-unsupported-modes-from-the-.patch
recipes-bsp/u-boot/files/upstream/0017-net-ti-icssg-prueth-use-constants-instead-of-hardcod.patch
recipes-bsp/u-boot/files/upstream/0018-net-ti-icssg-prueth-use-a-single-chn_name-variable-i.patch
recipes-bsp/u-boot/files/upstream/0019-net-ti-icssg-prueth-Add-port-speed-duplex-command.patch
recipes-bsp/u-boot/files/upstream/0020-net-ti-icssg-prueth-Add-shutdown-command.patch
recipes-bsp/u-boot/files/upstream/0021-net-ti-icssg-prueth-Auto-start-PRU-and-RTU-when-star.patch
recipes-bsp/u-boot/files/upstream/0022-config_distro_bootcmd-Add-platform-start-script-hook.patch
recipes-bsp/u-boot/files/upstream/0023-arm-dts-k3-am65-main-Add-ICSSG0-1-nodes.patch
recipes-bsp/u-boot/files/upstream/0024-iot2050-Add-ICSSG0-Ethernet-support.patch
recipes-bsp/u-boot/files/upstream/0025-iot2050-config-the-default-device-tree.patch
recipes-bsp/u-boot/files/upstream/0026-enable-soc-device-ID-driver.patch
recipes-bsp/u-boot/files/upstream/0027-iot2050-Add-support-for-flash-protect.patch
recipes-bsp/u-boot/files/upstream/0028-mtd-spi-Add-support-of-flash-protection-to-w25q128.patch
recipes-bsp/u-boot/u-boot-iot2050-2021.x-upstream.inc

The flash chip of IOT2050 is a Winbond chip and can reuse the same
logic of flash protection of STMICRO chips.
User can use `sf protect lock` and `sf protect unlock` commands to lock
& unlock the flash.

u-boot: Enable flash protection for IOT2050

---

recipes-app/switchserialmode/files/src/switchserialmode.c

The original code claimed to flip mode0 while it was toggling mode1, and
vice versa. While translating those comments into line names, that
became broken. Fix it, also by using better argument names for
gpio_set_mode.

switchserialmode: Fix flipped mode0/1 control

---

README.md
recipes-core/images/iot2050-image-example.bb
recipes-core/install-on-emmc/files/install-on-emmc-on-first-boot.service
recipes-core/install-on-emmc/files/install-on-emmc.sh
recipes-core/install-on-emmc/files/postinst
recipes-core/install-on-emmc/install-on-emmc_1.0.bb
wic/iot2050.wks

I think this is simpler than the so far officially documented (https://support.industry.siemens.com/tf/ww/en/posts/how-to-install-example-image-to-emmc/238947/?page=0&pageSize=10) pattern to use two media or to boot one first (to expand it, install the image into it, and then run the transfer manually.

Add support for interactive and automatic eMMC installation

---

recipes-core/install-on-emmc/files/install-on-emmc.sh

This is apparently needed to ensure that partx will find the partitions
fully written.

install-on-emmc: Sync to disk after writing eMMC

---

recipes-kernel/linux/files/0001-iot2050-add-iot2050-platform-support.patch
recipes-kernel/linux/files/0002-Add-support-for-U9300C-TD-LTE-module.patch
recipes-kernel/linux/files/0003-feat-Add-CP210x-driver-support-to-software-flow-cont.patch
recipes-kernel/linux/files/0004-fix-disable-usb-lpm-to-fix-usb-device-reset.patch
recipes-kernel/linux/files/0005-Fix-DP-maybe-not-display-problem.patch
recipes-kernel/linux/files/0006-fix-fix-the-hardware-flow-function-of-cp2102n24.patch
recipes-kernel/linux/files/0007-feat-add-io-expander-pcal9535-support.patch
recipes-kernel/linux/files/0008-setting-the-RJ45-port-led-behavior.patch
recipes-kernel/linux/files/0009-fix-clear-the-cycle-buffer-of-serial.patch
recipes-kernel/linux/files/0010-feat-extend-led-panic-indicator-on-and-off.patch
recipes-kernel/linux/files/0011-fix-can-not-auto-negotiate-to-100M-with-4-wire.patch
recipes-kernel/linux/files/0012-feat-change-mmc-order-using-alias-in-dts.patch
recipes-kernel/linux/files/0013-fix-PLL4_DCO-freq-over-range-cause-DP-not-display.patch

This addresses two issues:
reserved_memory -> reserved-memory, resolving the overwrite of unsecured
secure TEE memory (the fact that is unsecured is another issue, but of
the firmware)
reset-gpios -> reset-gpio, aligning to the binding specification of the
underlying Synopsys DesignWare PCIe (was papered over by
devm_gpiod_get_optional so far, accepting both)
Fixes #112 (well, not truly)
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

linux-iot2050: Fix device tree in 4.19 queue

---

recipes-kernel/linux/files/5.x-kernel/0001-iot2050-add-iot2050-platform-support.patch
recipes-kernel/linux/files/5.x-kernel/0002-Workaround-to-correct-DP-clock-to-154MHZ.patch
recipes-kernel/linux/files/5.x-kernel/0003-setting-the-RJ45-port-led-behavior.patch
recipes-kernel/linux/files/5.x-kernel/0004-feat-Add-CP210x-driver-support-to-software-flow-cont.patch
recipes-kernel/linux/files/5.x-kernel/0005-feat-add-io-expander-pcal9535-support.patch
recipes-kernel/linux/files/5.x-kernel/0006-feat-extend-led-panic-indicator-on-and-off.patch
recipes-kernel/linux/files/5.x-kernel/0007-Add-support-for-U9300C-TD-LTE-module.patch
recipes-kernel/linux/files/5.x-kernel/0008-feat-change-mmc-order-using-alias-in-dts.patch
recipes-kernel/linux/files/5.x-kernel/0009-dts-add-the-usb3.0-support.patch
recipes-kernel/linux/files/5.x-kernel/0010-dts-add-the-cp2102n-reset-pin-defination.patch
recipes-kernel/linux/files/5.x-kernel/0011-dts-reconfigure-pcie-node.patch
recipes-kernel/linux/linux-iot2050_5.4.74+.bb

as lack of property:num-lanes,there is no any phy link,the board can not
detect pcie devices.

dts: reconfigure pcie node

---

recipes-app/iot2050setup/files/iot2050setup.py

Simply a call to dpkg-reconfigure tzdata, just simpler to find for
Debian beginners.

iot2050setup: Add time zone command

---

recipes-kernel/linux/files/0001-iot2050-add-iot2050-platform-support.patch
recipes-kernel/linux/files/0002-Add-support-for-U9300C-TD-LTE-module.patch
recipes-kernel/linux/files/0003-feat-Add-CP210x-driver-support-to-software-flow-cont.patch
recipes-kernel/linux/files/0004-fix-disable-usb-lpm-to-fix-usb-device-reset.patch
recipes-kernel/linux/files/0005-Fix-DP-maybe-not-display-problem.patch
recipes-kernel/linux/files/0006-fix-fix-the-hardware-flow-function-of-cp2102n24.patch
recipes-kernel/linux/files/0007-feat-add-io-expander-pcal9535-support.patch
recipes-kernel/linux/files/0008-setting-the-RJ45-port-led-behavior.patch
recipes-kernel/linux/files/0009-fix-clear-the-cycle-buffer-of-serial.patch
recipes-kernel/linux/files/0010-feat-extend-led-panic-indicator-on-and-off.patch
recipes-kernel/linux/files/0011-fix-can-not-auto-negotiate-to-100M-with-4-wire.patch
recipes-kernel/linux/files/0012-feat-change-mmc-order-using-alias-in-dts.patch
recipes-kernel/linux/files/0013-fix-PLL4_DCO-freq-over-range-cause-DP-not-display.patch
recipes-kernel/linux/files/0014-serial-8250-8250_omap-Fix-possible-interrupt-storm.patch
recipes-kernel/linux/linux-iot2050_4.19.94+.bb

Pending upstream: https://lkml.org/lkml/2021/5/11/717. Seen so far only
on the MCU (Arduino) UART under synthetic test-case load.

linux-iot2050: Add patch that fixed UART IRQ storm possibility

---

recipes-app/node-red-preinstalled-nodes/node-red-preinstalled-nodes_0.1.bb
recipes-core/images/iot2050-image-example.bb

Just like in meta-iot2000, we need to create a package.json in the
.node-red folder that contains our preinstalled nodes. Otherwise,
Node-RED removes them on any update of individual nodes.

node-red: Fix update via palette of preinstalled nodes

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

Pad images that are not erase-size aligned and terminate earlier. This
avoids needless updates of the flash with zeros.

iot2050-firmware-update: Account for incomplete images

---

recipes-app/tcf-agent/tcf-agent.bb

The github repo has been removed, for whatever reasons, and the
git.eclipse.org repo seems to be the official one. But it took quite
some guesswork to find this undocumented URL. What a mess.

tcf-agent: Switch URL to git.eclipse.org

---

recipes-app/iot2050setup/files/iot2050setup.py

mainwindow initialization must be out of the try block, and we should
not swallow exceptions, rather close the window first and then dump them
properly.

iot2050setup: Fix cleanup in case of exceptions

---

conf/distro/iot2050-debian.conf
conf/distro/preferences.npm-backport

Urgent, fixes the currently broken build. See also https://support.industry.siemens.com/tf/ww/en/posts/cant-build-meta-iot2050-image-anymore/266848/?page=0&pageSize=10.

fix apt preferences

---

recipes-core/install-on-emmc/files/install-on-emmc.sh

partx -a is recommended to inform the kernel about new partitions now
visible when rescanning the device. But that seems to be only one piece.
It may take some time for the device node to show up. So wait until that
happened. This should fix errors like
install-on-emmc.sh[175]: Updating partition UUID of eMMC rootfs
install-on-emmc.sh[175]: partx: specified range <1:0> does not make sense
install-on-emmc.sh[175]: mount: /mnt: special device /dev/mmcblk1p1 does not exist.
While I'm still waiting for the reporter's feedback (https://support.industry.siemens.com/tf/ww/en/posts/cannot-boot-from-emmc/264499), I think it's better to merge this for the next release.

install-on-emmc: Fix partition table update after image writing

---

recipes-core/customizations-example/customizations-example_0.1-iot2050-debian.bb
recipes-core/customizations-example/files/20-assign-ethernet-names.rules
recipes-core/customizations-example/files/20-swap-ethernet-port.rules
recipes-core/customizations-example/files/eno1-default
recipes-core/customizations-example/files/postinst

I think this should go in before the release, to avoid renaming twice.

customizations-example: Resolve renaming race when swapping eth0/eth1

---

recipes-app/iot2050setup/files/iot2050setup.py

as only take ssh login and serial login into consider, missing the
dp condition.
so only when login from serial, it would resize the window.
it would ignore other option

iot2050setup: fix the issue that it would hang when using dp login

---

recipes-bsp/u-boot/files/0001-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/0002-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0003-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0004-net-eth-uclass-eth_get_dev-based-on-SEQ_ALIAS-instea.patch
recipes-bsp/u-boot/files/0005-net-eth-uclass-call-stop-only-for-active-devices.patch
recipes-bsp/u-boot/files/0006-misc-uclass-Introduce-misc_init_by_ofnode.patch
recipes-bsp/u-boot/files/0007-soc-ti-pruss-add-a-misc-driver-for-PRUSS-in-TI-SoCs.patch
recipes-bsp/u-boot/files/0008-remoteproc-pruss-add-PRU-remoteproc-driver.patch
recipes-bsp/u-boot/files/0009-net-ti-icssg-prueth-Add-ICSSG-ethernet-driver.patch
recipes-bsp/u-boot/files/0010-arm-dts-k3-am65-main-Add-msmc_ram-node.patch
recipes-bsp/u-boot/files/0011-arm-dts-k3-am654-base-board-u-boot-Add-icssg-specifi.patch
recipes-bsp/u-boot/files/0012-arm-dts-k3-am65-main-Add-pruss-nodes-for-ICSSG2.patch
recipes-bsp/u-boot/files/0013-arm64-dts-ti-am654-base-board-add-ICSSG2-Ethernet-su.patch
recipes-bsp/u-boot/files/0014-configs-am65x_evm_a53_defconfig-Enable-prueth-config.patch
recipes-bsp/u-boot/files/0015-net-ti-icssg-prueth-Drop-unsupported-modes-from-the-.patch
recipes-bsp/u-boot/files/0016-net-ti-icssg-prueth-use-constants-instead-of-hardcod.patch
recipes-bsp/u-boot/files/0017-net-ti-icssg-prueth-use-a-single-chn_name-variable-i.patch
recipes-bsp/u-boot/files/0018-net-ti-icssg-prueth-Add-port-speed-duplex-command.patch
recipes-bsp/u-boot/files/0019-net-ti-icssg-prueth-Add-shutdown-command.patch
recipes-bsp/u-boot/files/0020-net-ti-icssg-prueth-Auto-start-PRU-and-RTU-when-star.patch
recipes-bsp/u-boot/files/0021-config_distro_bootcmd-Add-platform-start-script-hook.patch
recipes-bsp/u-boot/files/0022-arm-dts-k3-am65-main-Add-ICSSG0-1-nodes.patch
recipes-bsp/u-boot/files/0023-iot2050-Add-ICSSG0-Ethernet-support.patch
recipes-bsp/u-boot/files/0024-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0025-arm-dts-update-flash-layout.patch
recipes-bsp/u-boot/files/0026-Modify-the-icssg0-pru1-and-rtu1-loadaddress.patch
recipes-bsp/u-boot/files/0027-board-siemens-Add-support-to-select-pg1-and-pg2-boar.patch
recipes-bsp/u-boot/files/0028-HACK-arm-mach-k3-am6_init-Prioritize-MSMC-traffic-ov.patch
recipes-bsp/u-boot/u-boot-iot2050_2021.04.bb

As we found when using iperf to test the ethernet.transitonal kernel with sysfw3.x firmware
would has some tcp protocol error(zero bits)
As the transitonal kernel would compatible with sysfw2.x and sysfw3.x.
Inclued this patch to fix ethernet related problem.

u-boot:HACK: arm: mach-k3: am6_init: Prioritize MSMC traffic

---

recipes-core/customizations-example/files/20-assign-ethernet-names.rules

Use phys_port_name as reliable attribute to tell the different ports of
prueth apart.

customizations-example: Make Ethernet renaming rule more robust

---

recipes-bsp/u-boot/files/0001-arm-mach-k3-am6_init-Prioritize-MSMC-traffic-over-DD.patch
recipes-bsp/u-boot/files/0002-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/0003-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0004-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0005-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0006-watchdog-Allow-to-use-CONFIG_WDT-without-starting-wa.patch
recipes-bsp/u-boot/files/0007-iot2050-Enable-watchdog-support-but-do-not-auto-star.patch
recipes-bsp/u-boot/files/0008-sf-query-the-write-protect-status-before-operating-t.patch
recipes-bsp/u-boot/u-boot-iot2050_2021.04.bb

When flash protect is enable,write or erase the flash would not reminder any error.
It would show "erase Ok",but actually erasing the flash is not success
Check the write protection status before operating the device

u-boot:sf:get the permission before operating the device

---

recipes-bsp/u-boot/files/0003-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0004-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0005-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0006-watchdog-Allow-to-use-CONFIG_WDT-without-starting-wa.patch
recipes-bsp/u-boot/files/0007-iot2050-Enable-watchdog-support-but-do-not-auto-star.patch
recipes-bsp/u-boot/files/0008-sf-Querying-write-protect-status-before-operating-th.patch

Use strncmp to compare the board name to check if the board is
advanced or not.
Signed-off-by: Su Bao Cheng <baocheng.su@siemens.com>

u-boot: fix the string compare for the board name

---

recipes-core/images/iot2050-image-base.bb

By now, many users are familiar with building own imaging to get latest
features and fixes. As we are now requiring a firmware update for
supporting the 5.10 kernel, reports arrive that things are unexpectedly
broken.
Warn about this situation prominently during the image build. This
warning can later be adjusted to "requires firmware release ..." or
completely dropped again.

iot2050-image: Warn users about firmware incompatibility

---

recipes-bsp/u-boot/files/0001-arm-mach-k3-am6_init-Prioritize-MSMC-traffic-over-DD.patch
recipes-bsp/u-boot/files/0002-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/0003-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0004-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0005-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0006-watchdog-Allow-to-use-CONFIG_WDT-without-starting-wa.patch
recipes-bsp/u-boot/files/0007-iot2050-Enable-watchdog-support-but-do-not-auto-star.patch
recipes-bsp/u-boot/files/0008-sf-Querying-write-protect-status-before-operating-th.patch
recipes-kernel/linux/linux-iot2050-rt_5.10.59-rt52.bb

This primarily fixes forwarding of the MAC addresses from the info
structure to the Linux device tree. It furthermore aligns the DT with
the upstream pending version and removes code that is dead until prueth
support is (re-)added.

u-boot-iot2050: Update patches

---

recipes-kernel/linux/linux-iot2050-rt_5.10.59-rt52.bb

RT patches are only available under "older" when newer releases appear.

linux-iot2050-rt: Use stable patch URL

---

recipes-app/iot2050setup/files/iot2050setup.py

1.The result of the regular expression match contains the null character,
which causes the subsequent comparison to fail
2.Wait for the sync to complete,then reset the bridge

iot2050setup: fix the serial port switch function

---

recipes-bsp/u-boot/files/0001-arm-mach-k3-am6_init-Prioritize-MSMC-traffic-over-DD.patch
recipes-bsp/u-boot/files/0002-arm-dts-Add-IOT2050-device-tree-files.patch
recipes-bsp/u-boot/files/0003-board-siemens-Add-support-for-SIMATIC-IOT2050-device.patch
recipes-bsp/u-boot/files/0004-arm64-dts-ti-k3-am65-mcu-Add-RTI-watchdog-entry.patch
recipes-bsp/u-boot/files/0005-watchdog-rti_wdt-Add-support-for-loading-firmware.patch
recipes-bsp/u-boot/files/0006-watchdog-Allow-to-use-CONFIG_WDT-without-starting-wa.patch
recipes-bsp/u-boot/files/0007-iot2050-Enable-watchdog-support-but-do-not-auto-star.patch
recipes-bsp/u-boot/files/0008-sf-Querying-write-protect-status-before-operating-th.patch
recipes-bsp/u-boot/files/0009-boards-siemens-iot2050-Ignore-network-errors-during-.patch
recipes-bsp/u-boot/u-boot-iot2050_2021.04.bb

Needed to prevent that the red error LED is turned on even during
successful boots.

u-boot-iot2050: Add patch that prevents spurious red LED signal

---

recipes-app/node-red-gpio/files/0005-Add-configurable-GPIO-mode-for-DIN.patch
recipes-app/node-red-gpio/node-red-gpio_0.0.6-IOT2050.bb

GPIO mode wasn't set correctly. Add the possibility to set mode via
node red DIN with 4 possible values from mraa: Strong, Pull-up,
Pull-down, Hiz.
Fixes #135
Signed-off-by: Ivan Mikhaylov <ivan.mikhaylov@siemens.com>

node-red-gpio: Add configurable GPIO mode for DIN

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

Use device tree board name to distinguish board type, instead of using
the soc id, due to the later is proven to be not a solid method.
Signed-off-by: Su Bao Cheng <baocheng.su@siemens.com>

iot2050-firmware-update: Use device tree board name

---

recipes-bsp/optee-os/optee-os-iot2050_3.12.0.bb

If downstream creates a new machine based on conf/machine/iot2050.conf
the dependency to optee-os-iot2050 is no longer fulfilled. Change
OPTEE_NAME from `${MACHINE}` to `iot2050`.
Signed-off-by: Quirin Gylstorff <quirin.gylstorff@siemens.com>

optee-os-iot2050: Make Name compatible with downstream machine

---

recipes-app/switchserialmode/files/src/switchserialmode.c

When switch serial mode, sometimes cp2102n would fall into bootloader mode.
the device can not be identified as /dev/ttyUSB0.
Add a 60ms dealy to make sure the settings have time to be set before reset.

bugfix:switchserialmode:make sure the settings have time to be set

---

conf/distro/iot2050-debian.conf
conf/machine/iot2050.conf

Since the u-boot recipes have been splitted for PG1 and PG2, the example
image building uses the wrong upstream provider, due to the PREFERRED_VERSION_
prefix is not defined for the new -pgX PN.
Meanwhile the preferred u-boot-iot2050-config provider should be
adjust accordingly.
Signed-off-by: Su Baocheng <baocheng.su@siemens.com>

Fix the wrong u-boot-iot2050 provider when building example image

---

recipes-core/images/iot2050-image-base.bb

This reverts commit 597839ae5d8fcb1f0c51e61e8a220814ff6008a8.
New firmware 1.2.1 is now officially available.

Revert "iot2050-image: Warn users about firmware incompatibility"

---

recipes-core/customizations-base/customizations-base_0.1-iot2050-debian.bb
recipes-core/customizations-base/files/hosts.tmpl
recipes-core/customizations-base/files/postinst.tmpl

This avoids conflicts with other packages that want to adjust this file,
e.g. docker.io. And it's simpler because we can now let netbase deliver
the foundation.
This should resolve #262 (once merged into stable as well).

customizations-base: Do not package /etc/hosts, modify it

---

.github/workflows/free-disk-space/action.yml
.github/workflows/main.yml
.gitignore
.gitlab-ci.yml
Kconfig
README.md
conf/machine/iot2050.conf
kas-iot2050-swupdate.yml
kas/iot2050.yml
recipes-bsp/patch-u-boot-env/files/patch-u-boot-env.config
recipes-bsp/patch-u-boot-env/files/patch-u-boot-env.service
recipes-bsp/patch-u-boot-env/files/patch-u-boot-env.sh
recipes-bsp/patch-u-boot-env/files/postinst
recipes-bsp/patch-u-boot-env/patch-u-boot-env_0.1.bb
recipes-core/data-partition/data-partition_0.1.bb
recipes-core/data-partition/files/data.mount.tmpl
recipes-core/data-partition/files/postinst
recipes-core/images/files/sw-description.tmpl
recipes-core/images/iot2050-image-swu-example.bb
recipes-core/swupdate-complete-update-helper/files/complete_update.sh
recipes-core/swupdate-complete-update-helper/swupdate-complete-update-helper_0.1.bb
recipes-core/swupdate-handler-roundrobin/files/swupdate.handler.u-boot.ini
recipes-core/swupdate-handler-roundrobin/swupdate-handler-roundrobin_%.bbappend
recipes-core/swupdate/swupdate_%.bbappend
recipes-core/watchdog/files/99-watchdog.conf
recipes-core/watchdog/iot2050-watchdog.bb
wic/iot2050-swu.wks.in

This PR adds a swupdate configuration to meta-iot2050. It uses [isar-cip-core](https://gitlab.com/cip-project/cip-core/isar-cip-core) as base.
To build the image use:
```shell
./kas-container build kas-iot2050-example.yml:kas/opt/swupdate-example.yml
```
This image will modify the u-boot-environment during first-boot to add the necessary variable for swupdate.
This fixes Issue #50.

Add swupdate

---

.github/workflows/free-disk-space/action.yml
.github/workflows/main.yml
Kconfig
kas/iot2050.yml
kas/opt/no-coral.yml
recipes-core/images/iot2050-image-example.bb
recipes-security/openssl/openssl_latest.bb

Add Google Coral packages to the example image by default. This increases our storage demand, so include the github running VM cleanup that @gylstorffq developed for #115.

Integrate support for Coral 

---

.github/workflows/free-disk-space/action.yml
kas/iot2050.yml

Fix the swupdate build error by bumping isar-cip-core to ed318f247beef10e0433c6ed699b4c1ab008fa6a.
Also bump ISAR and meta-coral refspec to drop the patches introduced by https://github.com/siemens/meta-iot2050/pull/259.
On my machine the build needs currently 52G disk memory.
An out-of-disk error occurred during building. Free disk space by purging the following packages:
- dotnet
- google-chrom-stable
-  temurin java
- google-cloud-sdk
- hhvm
- azure-cli
- llvm*
Also delete all content below /opt and /usr/local.
This leads to free disk space of 65G.
This is a workaround until a slim build environment is provided, see https://github.com/actions/virtual-environments/issues/5098.

Fix SWUpdate build

---

recipes-core/swupdate/swupdate_%.bbappend

Use DEB_BUILD_PROFILES to set pkg.swupdate.bpo to avoid
error messages during accessing mtd<X> device.
This fixes #265 .

SWUpdate: Use DEB_BUILD_PROFILES

---

recipes-bsp/u-boot/files/0007-arm-dts-iot2050-Use-the-auto-generator-nodes-for-fdt.patch
recipes-bsp/u-boot/files/0008-iot2050-Update-firmware-layout.patch

The introduction of generated config nodes had another trap which is now
resolved.
Should obsolete #278.

u-boot-iot2050: Update patch queue to fix detection of Advanced devices

---

recipes-security/openssl/openssl_latest.bb

This is neither needed anymore because we have no additional version in
out apt sources. Nor does it work when there is an update in -security
while the pinning pulls from the release repo:
The following packages will be DOWNGRADED:
libssl1.1
0 upgraded, 580 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.

openssl: Drop pinning to BASE_DISTRO_CODENAME

---

recipes-security/openssl/openssl_latest.bb

This is neither needed anymore because we have no additional version in
out apt sources. Nor does it work when there is an update in -security
while the pinning pulls from the release repo:
The following packages will be DOWNGRADED:
libssl1.1
0 upgraded, 580 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

Fix openssl build in stable branch

---

kas/iot2050.yml
recipes-core/images/iot2050-image-example.bb

As could not compile the 32bit application on the native machine.
it should use cross-compile method.
Some 32bit applications need to be transplanted and applied on iot2050,
so add armhf compat libraries.
besides enable compt support,can get corresponding supported sdk

iot2050-image-example: add armhf compat libraries

---

recipes-core/regen-rootfs-uuid/files/regen-rootfs-uuid.sh

This both simplifies the logic and makes it robust against temporary
inconsistency after writing the rootfs via install-on-emmc.
As an alternative to #317.

regen-rootfs-uuid: Remove dependency on reading correct old UUID

---

isar-patches/0001-expand-on-first-boot-Resolve-errors-in-helper-script.patch
kas/iot2050.yml

Currently, expand-on-first-boot is broken for the "normal" example image
due to the previously added Isar patch for the swupdate image. Fix it.
Both patches will vanish on next Isar update.

Add Isar patch to fix expand-on-first-boot

---

recipes-core/images/iot2050-image-example.bb

Several new USB devices have their proprietary Windows drivers onboard,
especially WAN dongles.
they act like a flash storage,usb-modeswitch can switch  the device
from "usb-storage" to "usbserial".

iot2050-image-example: add mode switching tool for usb devices

---

recipes-core/images/iot2050-image-swu-example.bb

That class uses the same variable - but for the purpose of setting the
UUID value.
Reported-by: Vijai Kumar K <Vijaikumar_Kanagarajan@mentor.com>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

swupdate: Avoid variable name clash with image_uuid.bbclass

---

Kconfig

Fix the Kconfig for the secure boot on m.2 variant, so that
`kas-container menu` could show the secure boot options when the m.2
firmware target is chosen, especially the OTP provisioning options and
the firmware secure version.

kconfig: Secure boot for m.2 variant

---

.github/workflows/main.yml

As now we have another m.2 variant, the old wording for bootloaders
could not stand any more.
Reword the job name to `Bootloaders` to cover all variants, including
future variants, if any. Meanwhile reword the stage names to be more
accurate.
Signed-off-by: Baocheng Su <baocheng.su@siemens.com>

ci: Reword for bootloaders

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

there are some uboot env need to be reserved after firmware upgrade.
fill the reserved env at the reserved_uboot_env filed in the update.conf.json to
keep the uboot env after firmware upgrade

iot2050-firmware-update: preserve u-boot env variables across updates 

---

classes/npm.bbclass

While gyp needs /usr/bin/python, it will happily work with python3
(removing the need to to pull python2): use Debian's package
python-is-python3 instead of python
Signed-off-by: Cedric Hombourger <cedric.hombourger@siemens.com>

classes/npm: let gyp use python3

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

Based on CS feedback, by default, the environment variables in the json
field (suggested_preserved_uboot_env) will be retained.
And we provide an additional parameter '-r' to reset the environment environment variables

iot2050-firmware-update: add the option to reset uboot env

---

recipes-core/images/iot2050-image-example.bb

Currently,there is no ntp service by default,so can not
sync time automatic.
Using systemd-timesyncd daemon to do the time sync.

iot2050-image-example: Add systemd-timesyncd

---

kas/iot2050.yml

Upstream repo https://salsa.debian.org/python-team/packages/python-absl integrated by meta-coral has just removed the `debian/0.15.0-1` tag which is picked up by the meta-coral, this caused the building failed for both the master and the V1.3.1 tag.
The latest main of meta-coral has bump the python-absl to `debian/0.15.0-2`.
Signed-off-by: Baocheng Su <baocheng.su@siemens.com>
This fix #351 for the master branch

Bump the meta-coral version to latest main

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

After the update is completed, read back the content of the flash, calculate the hash value of the content and the write value, compare the two hash value to ensure the correctness of the written value.

iot2050-firmware-update: Add integrity check

---

recipes-core/customizations-example/customizations-example_0.1-iot2050-debian.bb
recipes-core/customizations-example/files/20-create-symbolic-link-for-serial-port.rules

For advanced board and basic board, serial port have different names For advanced board serial port named ttyUSB0, whereas for basic board, serial port named ttyS2
Another problem is when using 4G or 5G card go through USB signal, according to the probe sequence, ttyUSB0 may not represent serial port for advanced board.
So create a dev symbolic link ttyX30 represent serial port.

customizations-example: create a symbolic link for serial port

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update

Issue:
we used this tool on the previous release image found that if there were tow identical values will be used to sort higher. However, the backward value is used on the latest image.
It is unreasonable to have two identical environment variables in the same uboot env file. So remove the same environment variables from the default list to fix this issue.

iot2050-firmware-update: Fix env that preserved is not right

---

kas/iot2050.yml

Our build system has broken cause the bazel-bootstrap upstream changes.
the commit:
https://github.com/siemens/meta-coral/commit/914ab3abf6cc4460148964b832c4276e09cc071f
has fixed this issue.
The latest main branch needs the feature supported by the newer ISAR version.
the ISAR version we are using is v0.9, meta-coral would maintain an isar-v0.9
to compat isar version.
For long-term solution we need upgrade isar version.
Bump to the latest commit of meata-coral/isar-v0.9 branch to solve this problem

Bump meta-coral version

---

classes/npm.bbclass

This patch adds the NPM_INSTALL_FLAGS bitbake variable to add additional npm install flags.
The flags can be used to instruct npm modules to use system library dependencies instead of vendoring.

npm: add variable for additional install flags

---

recipes-app/node-red-gpio/node-red-gpio_0.3.0+git.bb

Separation of class LED selection and state control. The label of the LED corresponds to the silk screen of the iot2050.
There is a problem with the state switching of the old version, This refact would also fix it.

node-red-gpio: Refact decouple led and state control

---

.github/workflows/main.yml

The artifact name rule changes. There is no suffix .img Remove the .img suffix

CI: fix no artifacts upload

---

classes/npm.bbclass

This patch re-adds the NPM_INSTALL_FLAGS support that has been added in f9e004 and got lost when integrating the sbuild support in f810b9.

re-add NPM_INSTALL_FLAGS lost in sbuild transition

---

conf/layer.conf

This patch removes an absolute path pointing into the build host that also ends up in the sstate cache. By that, the target rootfs can be cached across multiple builds executed from different build directories. This is mainly important for gitlab-cloud-ci, as the build directory is mounted from the host and contains some random parts. For meta-iot2050 it might not be relevant, but this caching issue is inerhited by downstream users of this layer.
The general issue already has been discussed on the ISAR and KAS ML, leading to improvements in isar-sstate lint (for detection) and KAS for making the LAYERDIR variable relative to the TOPDIR. The last remaining bit is to fix the vardepvalue in the layers, as the LAYERDIR variable is immediately expanded, hence always contains an absolute path. …

improve caching of build on gitlab-runners

---

recipes-app/mraa/files/0001-gpio-Fix-JS-binding-regarding-interrupt-injections.patch
recipes-app/mraa/mraa_2.2.0+git.bb

See the included patch for more details. Related mraa PR is https://github.com/eclipse/mraa/pull/1102.
We may not get quick feedback from upstream, so I would recommend moving forward here already.

mraa: Add patch to fix "uv__has_active_reqs" assertions

---

recipes-app/mraa/mraa_2.2.0+git.bb

fix: add missing deps to shared libraries used by mraa
This patch adds the shlibs:Depends variable to the DEBIAN_DEPENS
variable. By that, automatically resolved runtime dependencies
are automatically added in their correct version.
This also fixes the bug that the libjson-c was missing.

fix: add missing deps to shared libraries used by mraa

---

recipes-app/iot2050setup/files/iot2050setup.py

Our reference design is UNO3.
Although you can query the specific pin through this:
https://cache.industry.siemens.com/dl/files/016/109779016/att_1018122/v1/iot2050_operating_instructions_en_en-US.pdf?download=true. 
But this is not very intuitive.
It shows the block diagram of our arduino board,
which is convenient for query and use.

iot2050setup: Add arduino board pinout

---

classes/npm.bbclass

The patch adds the common shlibs:Depends pattern to the npm class. This is required, as we use dpkg-raw as a base which does not add these as default. By adding it, all native dependencies of a package providing an NPM module are added automatically. This helps to avoid missing runtime dependencies and in general makes the dependency graph more precise.

fix: auto-resolve native deps of npm modules

---

classes/npm.bbclass
recipes-app/node-red-preinstalled-nodes/node-red-preinstalled-nodes_0.1.bb
recipes-app/node-red/node-red_2.2.3.bb
recipes-bsp/u-boot/u-boot-iot2050.inc
recipes-core/install-on-emmc/install-on-emmc_1.0.bb
recipes-core/iot2050-firmware/iot2050-firmware_0.1.bb
recipes-core/regen-rootfs-uuid/regen-rootfs-uuid_1.0.bb
recipes-core/watchdog/iot2050-watchdog.bb

This patch aligns the bitbake and the debian dependencies to improve partial builds. This also helps to reduce the dependency graph in general, which in turn allows for more concurrency in the build.
In addition, npm auditing is disabled at install time to significantly speed up the build.

Align bitbake and debian dependencies

---

recipes-bsp/secure-boot-otp-provisioning/secure-boot-otp-provisioning_0.1.bb

Refer to commit b4e085f, symbolic links outside of the source folder do not work now. Change them to hard links, and remove the keys from the generated source tarball.

secure-boot-otp-provisioning: Fix symbolic links

---

conf/machine/iot2050.conf
kas-iot2050-boot-pg1.yml
recipes-bsp/u-boot/u-boot-iot2050.inc

So that this information could also be used by other components, such as OPTee, when it warns the RPMB setup on PG1 devices.

Make the PRODUCT_GENERATION global

---

recipes-bsp/optee-os/optee-os-iot2050_3.19.0.bb

To avoid file name collision, which was true for optee since the client and the os shares the same version schema.

optee-os-iot2050: Rename download tarball name

---

recipes-bsp/optee-os/optee-os-iot2050_3.19.0.bb

PG1 device should not support RPMB based secure storage.

optee-os: Warn RPMB setup on PG1

---

recipes-core/customizations-example/customizations-example_0.1-iot2050-debian.bb
recipes-core/customizations-example/files/terminal_resize.sh

Console window has fixed columns and rows, there is no method to pass the window columns and rows to console terminal.
So it can not adjust the window size automatically.
This change would make adjust the console terminal column and row according to the actual terminal window size.
The most important benefit is that we can see the whole output when using journalctl systemctl and so on to output the debug info if the debug information is too long.
Autosize-console origin from iot2050setup tool.

customizations-example: Resizing a terminal

---

conf/distro/iot2050-debian.conf

This patch allows to derive custom swupdate images from the iot2050-debian distro. Previously, derived swu images could not be created as the abrootfs image name could not be overwritten, hence always pointed to the example image. This led to hard-to-debug situations where the boot failed as the image UUIDs did not match.

allow to override initramfs conf of iot2050-debian

---

recipes-core/images/iot2050-image-example.bb
recipes-core/images/iot2050-package-selections.inc

This patch carves out the package selections from the example image. The selections provide great value for downstream users that do not want to base their image on the example image, but still want to avoid re-creating these selections to e.g. make wifi work.

make example image package selections reusable

---

README.md
recipes-core/swupdate-complete-update-helper/files/complete_update.sh

This was forgotten when migrating from U-Boot script-based switching to EFI Boot Guard. Simplify the complete_update.sh script at this chance as there is no longer a need to reset any state after a rollback.
@gylstorffq

swupdate: Align completion helper and README to EFI Boot Guard schema

---

kas/iot2050.yml

update bazel-bootstrap to v4.2.2. The old jc-4.1.0 branch is removed from salsa repo.

Update meta-coral to fix CI

---

recipes-bsp/u-boot/files/0033-iot2050-Refactor-the-m.2-and-minipcie-power-pin.patch
recipes-bsp/u-boot/u-boot-iot2050_2022.01.inc

Issue is that sometimes, some miniPCIE card hangs, due to firmware/software issue. Such hang could not be recovered by software reset, since it is not power on reset.
However, the power supply design on M.2 variant, that control the 3.3V power pin through a GPIO is proven to work against such scenario. With this GPIO, during boot, a POR will be triggered to fully recover the miniPCIE or M.2 module.
So port this design also to the miniPCIE variants.
The target branch is stable/V01.03

u-boot-iot2050: Make m.2 power control also avaiable to minipcie

---

recipes-core/images/iot2050-image-example.bb
recipes-security/openssl/openssl_latest.bb

The openssl (target version, arm64) should be installed into the example image, not the openssl-compat (armhf version).
Meanwhile integrate the libssl1.1-compat for armhf compatible architecture.
Test result:
```shell
root@iot2050-debian:~# apt list --installed | grep ssl
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
libssl-dev/now 1.1.1n-0+deb11u4+iot2050 arm64 [installed,local]
libssl1.1/now 1.1.1n-0+deb11u4+iot2050 arm64 [installed,local]
libssl1.1/now 1.1.1n-0+deb11u4+iot2050 armhf [installed,local]
openssl/now 1.1.1n-0+deb11u4+iot2050 arm64 [installed,local]
```

iot2050-example-image: Fix wrongly installed openssl armhf

---

recipes-bsp/u-boot/README.md
recipes-bsp/u-boot/files/rpmb-setup.cfg
recipes-bsp/u-boot/u-boot-iot2050.inc
recipes-core/images/iot2050-package-selections.inc

Before some manual steps were required under u-boot console to trigger
the RPMB key provisioning, this was not so friendly for both the users
and the factory during manufactoring.
With this change, manual trigger is never required. Now by booting the
special firmware, the RPMB key is auto provisioned. And the result could
be checked both from frimware booting log and from linux `mmc` command.
Although, with a well equiped kernel image - with CONFIG_TEE_STMM_EFI or
CONFIG_TCG_FTPM_TEE enabled, it is also possible to auto provision the
RPMB key by a simple booting of that OS image, this brings extra
dependency on the OS image. It's better for the bootloader to finish
this task by its own, which benifits for some operation envioronment,
such as the manufactoring.

Automate the RPMB key pairing

---

recipes-kernel/linux/files/patches-5.10/0210-efi-Add-tee-based-EFI-variable-driver.patch
recipes-kernel/linux/linux-iot2050-5.10.inc

This one is based on v5 that is now staged in efi-next.

linux-iot2050: Update patch for TEE-based EFI variable driver

---

.github/workflows/main.yml

This could save some resources, also makes the queue shorter,
environmentally friendly :)

ci cancel in progress for same branch

---

kas/iot2050.yml
recipes-core/images/iot2050-image-swu-example.bb
wic/iot2050-swu-secure.wks.in
wic/iot2050-swu.wks.in

Several bits from the EOSS CIP demo, now refactored for mainline. These are updating SWUpdate itself and also address a blind window of the watchdog during initramfs operations.
Currently in draft until isar-cip-core next becomes master.

SWUpdate improvements

---

kas/opt/rpmb-setup.yml
kas/opt/secure-boot.yml
recipes-bsp/optee-os/optee-os-iot2050_3.21.0.bb
recipes-bsp/u-boot/files/0020-configs-Increase-malloc-size-after-relocation.patch
recipes-bsp/u-boot/u-boot-iot2050_2022.10.inc

Currently the RPMB key writing does not work:
1st issue was u-boot SPL complaining:
| alloc space exhausted
| Could not get FIT buffer of 1057180 bytes
|         check CONFIG_SYS_SPL_MALLOC_SIZE
This is fixed by expanding the heap size for malloc_simple.
Then comes to this issue:
| IOT2050> setenv -e -nv -bs -rt pairing 1
| I/TC: Reserved shared memory is enabled
| I/TC: Dynamic shared memory is enabled
| I/TC: Normal World virtualization support is disabled | I/TC: Asynchronous notifications are disabled
| E/LD:  init_elf:486 sys_open_ta_bin(ed32d533-99e6-4209-9cc0-2d72cdd998a7) | E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff0009 | Unable to open OP-TEE session (err=-5)
| mm_communicate failed!
| Error: Cannot initialize UEFI sub-system, r = 3
This is due to the StMM …

Fix for RPMB key writing

---

recipes-bsp/u-boot/files/0021-configs-iot2050-Enabled-keyed-autoboot.patch
recipes-bsp/u-boot/u-boot-iot2050_2022.10.inc

This shall avoid accidental interruptions of the boot process.

u-boot-iot2050: Backport keyed autoboot patch

---

recipes-bsp/k3-rti-wdt/k3-rti-wdt_1.2.bb
recipes-bsp/u-boot/files/0022-Add-a-reserved-memory-for-watchdog.patch
recipes-bsp/u-boot/u-boot-iot2050_2022.10.inc
recipes-kernel/linux/files/patches-5.10/0221-dt-bindings-watchdog-ti-rti-wdt-Add-support-for-WDIO.patch
recipes-kernel/linux/files/patches-5.10/0222-arm64-dts-ti-Add-reserved-memory-for-watchdog.patch
recipes-kernel/linux/files/patches-5.10/0223-watchdog-rit_wdt-Add-support-for-WDIOF_CARDRESET.patch

This patch adds the WDIOF_CARDRESET support for the TI AM65x platform
watchdog, to know if the board reboot is due to a watchdog reset.
This is done via reserved memory(RAM), which indicates if specific
info saved in k3-rti-wdt, triggering the watchdog reset in last boot.

iot2050:watchdog: Add support for WDIOF_CARDRESET

---

.github/workflows/free-disk-space/action.yml
conf/distro/iot2050-debian.conf
isar-patches/0001-optee-client-Fix-native-arm64-build.patch
kas/iot2050.yml
recipes-core/images/iot2050-image-example.bb

Drop obsolete bullseye-backports / fix CI / fix arm64 native build / fix Node-RED disabling

---

Kconfig

Due to the introduction of the new SM variant, the current wording for firmware need be adjusted.

Kconfig: Reword firmware images type to add SM variant

---

recipes-bsp/secure-boot-otp-provisioning/README.md

Change the TUI method description according to the latest Kconfig wordings.
Meanwhile make the third key generation not optional, to trim the operation branches.

secure-boot-otp-provisioning: Reword the README.md

---

recipes-kernel/linux/files/patches-6.1/0086-net-ti-icssg-config-add-SR1.0-specific-configuration.patch
recipes-kernel/linux/files/patches-6.1/0087-net-ti-icssg-prueth-add-SR1.0-specific-configuration.patch
recipes-kernel/linux/files/patches-6.1/0088-net-ti-icssg-classifier-Add-support-for-SR1.0.patch
recipes-kernel/linux/files/patches-6.1/0089-net-ti-icssg-config-Add-SR1.0-configuration-function.patch
recipes-kernel/linux/files/patches-6.1/0090-net-ti-icssg-ethtool-Adjust-channel-count-for-SR1.0.patch
recipes-kernel/linux/files/patches-6.1/0091-net-ti-iccsg-prueth-Add-necessary-functions-for-SR1..patch
recipes-kernel/linux/files/patches-6.1/0092-net-ti-icssg-prueth-Wire-up-support-for-SR1.0.patch
recipes-kernel/linux/files/patches-6.1/0093-net-ti-icss_iep-Add-SR1-support.patch
recipes-kernel/linux/files/patches-6.1/0094-arm64-dts-ti-iot2050-Add-icssg-prueth-nodes-for-PG1-.patch

This is widely a backport for current under-review upstream patches to re-add SR1.0 prueth support.
@diogo-ivo

linux-iot2050: Re-add support for SR1.0 prueth to the 6.1-cip kernel

---

recipes-app/iot2050-event-record/README.md
recipes-app/iot2050-event-record/files/iot2050-event-record.conf
recipes-app/iot2050-event-record/files/iot2050-event-record.py

Currently it is impossible to get the precise threshold values for tilting and uncovering threshold, make sensors' threshold values configurable.

iot2050-event-record: Make sensors' threshold configurable

---

recipes-bsp/trusted-firmware-a/trusted-firmware-a-iot2050_2.8.10.bb

* Snapshot of trusted-firmware-a (TFA) is no more accessible, so move to git usage.
* Unable to fetch lts-v2.8.10 so, version updated to 2.9.0

iot2050: Migrate trusted-firmwar-a to git

---

wic/iot2050-swu-secure.wks.in
wic/iot2050-swu.wks.in

This patch refactors the WKS script w.r.t how the rootfs is distributed across multiple partitions. Previously we used rootfs-dir with a full rootfs paths plus the sub directory. However, this is not ideal, as the relation to the rootfs folder is lost and also the new rootfs dir is technically not a rootfs. While this aparently did not create any issues in meta-iot2050, we still believe it is semantically incorrect.
This patch switches that over to the WIC option --change-directory that is provided exactly for this use-case and only deploys a subdirectory without loosing the rootfs relation with the permissions pseudo dir.

refactor: use change-dir to split rootfs parts

---

kas-iot2050-example.yml
recipes-app/board-conf-tools/files/board-conf-tools/board-bootup-conf.py
recipes-app/mraa/files/0004-iot2050-Add-support-for-the-new-IOT2050-SM-variant.patch
recipes-app/mraa/files/0005-gpio-chardev-init-compatibility.patch
recipes-app/mraa/files/0006-gpio-chardev-add-support-for-more-direction-flags.patch
recipes-app/mraa/files/0007-gpio-chardev-fix-ressource-handling.patch
recipes-app/mraa/files/0008-iot2050-add-helper-function-to-convert-gpio-number-t.patch
recipes-app/mraa/files/0009-iot2050-add-support-for-gpio-chardev-interface.patch
recipes-app/mraa/files/0010-iot2050-fix-pinmux-handling-of-user-pin.patch
recipes-app/mraa/files/20-mraa-permissions.rules
recipes-app/mraa/mraa_2.2.0+git.bb

This MR fixes some issues related the MRAA API access, as non-root user.
The following things have been changed/fixed:
1. Add gpio chardev support for MRAA (switch from sysfs to chardev)
2. Add udev rules that adjust permissions and assign required groups to all interfaces
3. The PWM pins require a more special handling and need to be pre-allocated during boot. This avoids
timing problems when exporting those pins the first time via MRAA (see issue #29). 
4. Create an example (non-root) user that has been assigned to all required groups.
5. Fix MRAA pinmux handling for pin 20

Fix MRAA non-root access

---

recipes-bsp/u-boot/files/0012-qspi-iot2050-Add-temporary-workaround-for-the-QSPI-i.patch
recipes-bsp/u-boot/files/0013-board-iot2050-Reset-the-eMMC-when-it-isn-t-reachable.patch
recipes-bsp/u-boot/u-boot-iot2050_2023.10.bb

1. u-boot-iot2050: Add temporary workaround for the QSPI issue: 
After approximately 2 months of operation, the device may fail to check
the QSPI idle status. Here is the strange phenomenon: The QSPI remains
busy when checking the idle status, becoming idle once stop checking.
Providing a temporary workaround to bypass the QSPI idle checking.
2. u-boot-iot2050: Reset the eMMC when it isn't reachable: 
After approximately 2 months of operation with above workaround, the device
may fail to detect the eMMC when rebooting.  Providing a temporary workaround
to reset the eMMC if detection issues occur.
Related to https://github.com/siemens/meta-iot2050/issues/440.

Add temporary workaround for the reboot issues

---

recipes-app/iot2050-firmware-update/iot2050-firmware-update_0.5.bb

As some tools come from u-boot-tools package (e.g. mkenvimage) in iot2050-firmware-update script, its build recipe should include u-boot-tools package dependency. Otherwise, these necessary tools are not installed to image.

fix(iot2050-firmware-update): Add missing package dependency

---

.github/workflows/main.yml
recipes-bsp/u-boot/files/0018-arm-dts-iot2050-Enforce-DMA-isolation-for-devices-be.patch

The bootefi command leads to the kernel FDT being overwritten by the U-Boot FDT. Although the UKI's FDT ultimately takes precedence, this intermediate overwrite can cause the device to fail to apply the overlay.

u-boot-iot2050: Match kernel dts for bootefi issue

---

recipes-bsp/u-boot/u-boot-iot2050_2023.10.bb

[u-boot-iot2050: Update bb file to include missing patch](https://github.com/siemens/meta-iot2050/commit/51d92e019f3b7711f766c4b77e6974b8a923aa7c)
Address an oversight where the modification to the bb file was not
submitted.

u-boot-iot2050: Update bb file to include missing patch

---

recipes-app/iot2050-firmware-update/iot2050-firmware-update_0.5.bb

Isar commit 0816ae6e97d15712f6b8eb873311464263f5df59 changed the default architecture for dpkg-raw from "any" to "all". Having a task that assumes the generated package file ends with "_arm64.deb" (not great btw), set DPKG_ARCH to "any".

fix(firmware-update): explicitly set DPKG_ARCH to "any"

---

recipes-app/switchserialmode/switchserialmode_0.5.bb
recipes-core/images/iot2050-image-example.bb

Several Siemens products have a switchserialmode package. The version included in this repository is really designed for the IOT2050: note the hardware dependency in the name of the package by prefixing it with "iot2050-". The package uses a Provides clause for backward compatibility (both for Isar builds and for apt).

switchserialmode: suffix package with -iot2050

---

conf/distro/iot2050-debian.conf
kas/opt/upstream.yml

The kbuildtarget is not set in the iot2050-debian.conf, this is causing both the kernels (cip & upstream) are be parsed and generated in the build process, which causes the parsing stage is very slow when connecting to github is not good.

linux-iot2050: Add the missing kbuildtarget

---

recipes-app/mraa/mraa_2.2.0+git20220805.8b1c5493.bb

The upstream mraa project does not seem to create versions/tags for the changes they make (version 2.2.0 was released in 2020 but the project has continued to receive updates since). We anyhow have our own set of patches on-top that we also need to version. Use CHANGELOG_V to include PR into the version string of our mraa package. PR should be incremented whenever we change the upstream revision (SRCREV) and/or update our patches. This will help with binary distributions of the package (e.g. for users needing to pull packages on their IOT2050 using apt).

fix(packages): introduce PR in the version string for mraa

---

recipes-kernel/linux/files/patches-6.1/0099-spi-cadence-qspi-Workaround-potential-flash-writing-.patch

Some issues with writing to the flash were found, particularly at high frequencies where up to 50% of attempts would fail in certain cases. Disabling the DAC, Direct ACcess, has proven effective in addressing this issue. This commit uses indirect mode to mitigate the problem.
Workaround issue mentioned in PR https://github.com/siemens/meta-iot2050/pull/585 and it comes from upstream
cce2200dacd6d7e0501c3811f24f5216710968fb. Upstream has rolled back it
with 3cb2a2f7eebbb0752a834708e720a914e61841a1, ultimately the real
issue needs to be fixed.

linux-iot2050: Workaround potential flash writing issue

---

kas/iot2050.yml
recipes-app/iot2050-firmware-update/iot2050-firmware-update_0.5.bb

This update brings the initramfs customization and setting up DEBIAN_MULTI_ARCH = "foreign" by default if DPKG_ARCH = "all".

Update isar revision

---

recipes-app/iot2050-efivarfs-helper/iot2050-efivarfs-helper_1.0.0.bb

There have been modification in the iot2050-efivarfs-helper.tmpl but without any bump in the version (PV). This causes the downsteam projects to miss the changes when building with cached apt. Incldue PR in the recipe to show the modifications.

iot2050-efivarfs-helper: include PR to track changes

---

recipes-app/iot2050-firmware-update/files/iot2050-firmware-update.tmpl
recipes-app/iot2050-firmware-update/iot2050-firmware-update_1.0.0.bb

Plain string comparison fails for versions like "4.10" vs "4.2", causing incorrect results. This patch uses `packaging.version` to ensure proper semantic version comparison.

fix(firmware-update): use semantic version comparison

---

.github/workflows/main.yml

- Reduce unnecessary build triggers on every push
- Provide more granular control over build processes
- Enable PR builds from forks

ci: Optimize CI workflow for more controlled and efficient builds
